<div class="container">      
		  <div class="contacts">
		  <a name="contacts">
			<h2 class="lh-1">Контакты</h2>
			<p><strong>Телефоны:</strong> +7 (949) 405-68-46, +7 (949) 405-68-47
			<p><strong>Электронная почта:</strong> <a href="mailto:sosc1995@mail.ru">sosc1995@mail.ru</a>
			<p><strong>Директ в Telegram:</strong> <a href="https://t.me/burenie_donetsk?direct">https://t.me/burenie_donetsk?direct</a>
			<p><strong>Адрес:</strong> г. Донецк, ул. Фёдора Зайцева, 75
			<p>
			<div class="yandex-map">
				<div style="position:relative;overflow:hidden; width:100%"><a href="https://yandex.ru/maps?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:0px;">Яндекс Карты</a><a href="https://yandex.ru/maps/142/donetsk/house/ulitsa_fyodora_zaytseva_75/Z04YfgZgS0UAQFptfXV4eX5rYw==/?ll=37.810207%2C47.998287&utm_medium=mapframe&utm_source=maps&z=16.58" style="color:#eee;font-size:12px;position:absolute;top:14px;">Улица Фёдора Зайцева, 75 — Яндекс Карты</a><iframe src="https://yandex.ru/map-widget/v1/?ll=37.810207%2C47.998287&mode=search&ol=geo&ouri=ymapsbm1%3A%2F%2Fgeo%3Fdata%3DCgoxNDQ5NDk3ODAwEkbQoNC-0YHRgdC40Y8sINCU0L7QvdC10YbQuiwg0YPQu9C40YbQsCDQpNGR0LTQvtGA0LAg0JfQsNC50YbQtdCy0LAsIDc1IgoNpz0XQhU__j9C&z=16.58" width="560" height="400" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe></div>
			</div>
		  </div>
</div>
	  
	  <!-- FOOTER -->
      <footer class="container">
        <p class="float-end"><a href="#">Наверх</a></p>
        <p>
          &copy; 2026 ИП Пименов Юрий Юрьевич, ИНН 614028229496 &middot;
          <a href="#">Политика конфиденциальности</a>
        </p>
      </footer>
    </main>
    <script
      src="assets/dist/js/bootstrap.bundle.min.js"
      class="astro-vvvwv3sm"
    ></script>